# Generated by Django 5.1.5 on 2025-02-01 06:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyconsumption',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dailyconsumption',
            name='item',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dailyconsumption',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
