# Generated by Django 5.1.5 on 2025-02-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_dailyconsumption_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyconsumption',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='dailyconsumption',
            name='item',
            field=models.CharField(choices=[('Milk', 'Milk'), ('Curd', 'Curd'), ('Buttermilk', 'Buttermilk')], max_length=10),
        ),
        migrations.AlterField(
            model_name='dailyconsumption',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
